### ISSUE TITLE
Having trouble with psr log

### ISSUE THREAD

**Issue by guywhelan** [Clever/clever-php#37]
I'm having trouble with getting a psr log error after I install everything. 
Specifically, I am seeing this error:
**PHP Fatal error:  Class 'Psr\Log\NullLogger' not found in /path/to/Clever/Object.php on line 27**

If I comment out line 27 in Object.php I get back the results I was looking for. For instance if I request:

**$district = CleverDistrict::retrieve("MyDistrictID");**

I get back:
CleverDistrict Object
(
    [_auth:protected] => Array
        (
            [token] => (MyDistrictToken)
        )
[_values:protected] => Array
        (
            [id] => (MyDistrictID)
            [name] => My Application (Dev) Sandbox
        )
[logger:protected] => 
)

**Comment by meliaj** [comment]
I've updated our readme to make things a little clearer.

Assuming you've installed the dependencies already with Composer, you need to add this line to your PHP script as well to get Composer to autoload referenced packages:
```
require_once('/path/to/clever-php/vendor/autoload.php');
```
