### ISSUE TITLE
Events error on student contacts

### ISSUE THREAD

**Issue by tokersey** [Clever/clever-php#42]
Hello,

When cycling through events, the following error appears. It seem it is trying to get a StudentcontactsCreated model instead of the ContactsCreated model

`PHP Fatal error:  Uncaught Error: Class '\Clever\Model\StudentcontactsCreated' not found in vendor/clever/clever/lib/ObjectSerializer.php:306
Stack trace:
#0 vendor/clever/clever/lib/ObjectSerializer.php(316): Clever\ObjectSerializer::deserialize(Object(stdClass), '\\Clever\\Model\\S...', NULL)
#1 vendor/clever/clever/lib/ObjectSerializer.php(246): Clever\ObjectSerializer::deserialize(Object(stdClass), '\\Clever\\Model\\E...', NULL)
#2 vendor/clever/clever/lib/ObjectSerializer.php(316): Clever\ObjectSerializer::deserialize(Array, '\\Clever\\Model\\E...', NULL)
#3 vendor/clever/clever/lib/Api/EventsApi.php(423): Clever\ObjectSerializer::deserialize(Object(stdClass), '\\Clever\\Model\\E...', Array)
#4 vendor/clever/clever/lib/Api/EventsApi.php(363): Clever\Api\EventsApi->getEventsWithHttpInfo(20, '5a986ee in vendor/clever/clever/lib/ObjectSerializer.php on line 306`

**Comment by meliaj** [comment]
Thanks @tokersey - we're investigating
